### ISSUE TITLE
Enhancement Request: Add support for Great Expectations Rules as quality input/output

### ISSUE THREAD

**Issue by RyanBacastow** [datacontract/datacontract-specification#44]
Hello! Amazing work with this and the CLI. I was hopeful that perhaps others would be interested in support for Great Expectations in the same way that Soda and Monte Carlo are featured in the datacontract specification and the CLI. I am happy to help assist but may not be the right expert on GE API mapping.

**Comment by jochenchrist** [comment]
@saugerDecathlon added support for `datacontract export --format great-expectations` to last release of the CLI.

Import is more difficult to make it good, as Great Expectation is based on Python.

Maybe we should think towards a defined specification for Quality Checks so that we can import from and export to different formats.

**Comment by jochenchrist** [comment]
Let's discuss in #55 the future approach to define the quality in the Data Contract Specification.
